---
format:
  revealjs: 
    theme: dark
    footer: |
      Author: [Gabriel Mateus Bernardo Harrington](https://gmbernardoharrington.netlify.app/)<br>
      Last modified: 2022-12-05
    # footer: Test !expr 'paste("Air", "Quality")'
    slide-number: c/t
---

## Presentations

Presentation repository can be found [here](https://github.com/H-Mateus/presentations).

- Current Presentations:
    - [Cardiff DRI Exec - 2022](2022-12-05_reproducibility_workflow_proposal/index.html)
    - [IsCoS 2021 - Proteomic and bioinformatics analyses of plasma from SCI](iscos_sci_proteomics_2021-08-31/index.html)
    - [Reproducible Research - CDT 2021](reproducible_research_2021-04-30/index.html)

See the next slide for a full list

## All slide decks {.scrollable}

- [Cardiff DRI Exec - 2022](2022-12-05_reproducibility_workflow_proposal/index.html)
- [Cardiff DRI ECR - 2022](dri-ecr-talk_2022-10-25/index.html)
- [IPMAR proteomics - 2022](ipmar_proteomics_2022-06-01/index.html)
- [Gregynog DRI - 2022](gregynog_2022-04-28/index.html)
- [Reproducible Research - CDT 2021](reproducible_research_2021-04-30/index.html)
- [IsCoS 2021 - Proteomic and bioinformatics analyses of plasma from SCI](iscos_sci_proteomics_2021-08-31/index.html)
- [SCI and the liver - 2021](liver_sci_talk_2021-01-27/index.html)
- [SCI proteomics - 2020](proteomic_talk_2020-09-24/index.html)
